server:
  port: 8082
spring:
  application:
    name: fraud
#  datasource:
#    password: password
#    url: jdbc:postgresql://localhost:5432/fraud
#    username: sharan
  datasource:
    url: jdbc:mysql://localhost:3306/fraud
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true