server:
  port: 8765
spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/contract_tester
    password: password
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
my:
  file:
    path: /Users/sharan/final-year-project/backend/contractsDB